version: "3"

services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: fusionloom-ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - fusionloom_net

networks:
  fusionloom_net:
    external: true
