version: "3"

services:
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:latest
    container_name: fusionloom-sillytavern
    ports:
      - "8000:8000"
    volumes:
      - ${SILLYTAVERN_CONFIG_VOLUME}:/home/node/app/config
      - ${SILLYTAVERN_DATA_VOLUME}:/home/node/app/data
      - ${SILLYTAVERN_PLUGINS_VOLUME}:/home/node/app/plugins
      - ${SILLYTAVERN_EXTENSIONS_VOLUME}:/home/node/app/public/scripts/extensions/third-party
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - fusionloom_net
    platform: linux/arm64  # Specify ARM64 platform for Apple Silicon

networks:
  fusionloom_net:
    external: true
