version: "3"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: fusionloom-ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      # CPU-only optimizations
      - OLLAMA_CPU_ONLY=1
      # Adjust these based on the host system capabilities
      - OLLAMA_NUM_THREADS=8
      - OLLAMA_MAX_MEMORY=8G
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - fusionloom_net
    # Resource limits for CPU-only operation
    deploy:
      resources:
        limits:
          cpus: '0.8' # Use up to 80% of available CPU
          memory: 10G

networks:
  fusionloom_net:
    external: true
