version: "3"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: fusionloom-webui
    volumes:
      - ./data:/app/backend/data
      - ../../ui:/app/frontend/custom-ui
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount Docker socket for container management
    ports:
      - "8080:8080"
    environment:
      - WEBUI_VERSION=0.1
      - WEBUI_APP_NAME=FusionLoom
      - CUSTOM_UI_PATH=/app/frontend/custom-ui
      - OLLAMA_BASE_URL=http://fusionloom-ollama:11434
      - CONTAINER_ENGINE=docker
      - CONTAINER_NETWORK=fusionloom_net
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - fusionloom_net

networks:
  fusionloom_net:
    external: true
