version: "3"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: fusionloom-webui
    volumes:
      - ./data:/app/backend/data
      - ../../ui:/app/build
      # Removed Podman socket mount due to permission issues
    ports:
      - "8080:8080"
    environment:
      - WEBUI_VERSION=0.3
      - WEBUI_APP_NAME=FusionLoom
      - OLLAMA_BASE_URL=http://fusionloom-ollama:11434
      - CONTAINER_ENGINE=podman
      - CONTAINER_NETWORK=fusionloom_net
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - fusionloom_net

networks:
  fusionloom_net:
    external: true
