version: "3"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: fusionloom-webui
    volumes:
      - ./data:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      - WEBUI_VERSION=0.1
      - WEBUI_APP_NAME=FusionLoom
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - fusionloom_net

networks:
  fusionloom_net:
    driver: bridge
