version: "3"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: fusionloom-webui
    volumes:
      - ./data:/app/backend/data
      - /Users/spresgraves/Repositories/FusionLoom/ui:/app/build
      - /run/podman/podman.sock:/var/run/docker.sock:ro  # Mount Podman socket as Docker socket for compatibility
    ports:
      - "8080:8080"
    environment:
      - WEBUI_VERSION=0.1
      - WEBUI_APP_NAME=FusionLoom
      - CUSTOM_UI_ENABLED=false
      - OLLAMA_BASE_URL=http://fusionloom-ollama:11434
      - CONTAINER_ENGINE=podman
      - CONTAINER_NETWORK=fusionloom_net
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - fusionloom_net

networks:
  fusionloom_net:
    external: true
